### PR TITLE
Bump to 3.8

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Hi @traversaro, sorry to ping you, but do you have any idea what I’m doing around here on windows with metis?

**Comment by traversaro** [comment]
I may be missing something, but it seems to me that there is no explicit dependency on metis and on Windows metis it is not installed, while on *nix it is installed probably being a transitive dependency?

**Comment by Tobias-Fischer** [comment]
How embarrassing, I was sure I added it .. thank you!

**Pull request merged**
