### PR TITLE
Rebuilding 3.8

### PR DESCRIPTION
**Pull request by cduguet**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This rebuild is intended to make pycolmap 0.4.0, and consequently pixsfm 1.0 run.

### CODE REVIEW

**Comment by jakirkham** [comment]
Could you please share a bit more details on what issue is cropping up?

**Comment by cduguet** [comment]
@jakirkham pixsfm needs pycolmap 0.4.0 and ceres-solver 2.1.0 to work, which is explained in more detail in [this bug](https://github.com/conda-forge/pixsfm-feedstock/issues/17). 
However, [pinning pixsfm to the existing builds of pycolmap 0.4.0, colmap 3.8 and ceres-solver 2.1.0 is not working](https://github.com/conda-forge/pixsfm-feedstock/pull/18), and [it was suggested to rebuild colmap3.8, pycolmap0.4.0 to make it work](https://github.com/conda-forge/pixsfm-feedstock/pull/18#issuecomment-2083894406).

I'm very new at conda-forge, so I'm not what should be the right procedure to update a build of an old version of a package (3.8). I guess PR'ing into `main` is not the right step, since I'm getting many merge conflicts with the newest version?

**Comment by jakirkham** [comment]
@conda-forge-admin , please relint

**Comment by jakirkham** [comment]
Since it sounds like you already talked to Tobias about this and he is the maintainer here, went ahead and created the branch for the old version and retargeted this PR to it

Looks like the linter has a few suggestions. Also we will need to see how CI goes

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin please rerender

**Comment by Tobias-Fischer** [comment]
Thanks @cduguet

**Pull request merged**
