### PR TITLE
Win build

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
I think we need to wait until we have boost 1.76 in conda-forge.

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Actually we're missing vlfeat on Win.

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Needs https://github.com/conda-forge/cgal-cpp-feedstock/pull/28

**Comment by Tobias-Fischer** [comment]
@traversaro @wolfv have you this before by any chance? BLAS_LIBRARIES cannot be found on windows.

**Comment by traversaro** [comment]
> @traversaro @wolfv have you this before by any chance? BLAS_LIBRARIES cannot be found on windows.

Hi @Tobias-Fischer, at a first glance I could not find any obvious reason this is happening, I will try to debug this on a Windows machine in the next days.

**Comment by Tobias-Fischer** [comment]
Hi @traversaro, did you have a chance to look at this?

**Comment by traversaro** [comment]
Sorry, I completly forgot about this. I will look into this in the next days.

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Got much further after the rettender - just needs a NOMINMAX now I believe :).

**Comment by traversaro** [comment]
> @traversaro @wolfv have you this before by any chance? BLAS_LIBRARIES cannot be found on windows.

Just replying here as today I had the same problem, but the only reference I found online was this discussion.

Basically, if you install `libblas` on Windows by default it installs you the `mkl` variant, that it is not sufficient to make `find_package(BLAS)` succeed. To have `find_package(BLAS)` succeed, you need to install the `blas-devel` package.

**Pull request merged**
